done
diynyk/Exchange-Rates pull request #1
Opened 2021-03-12 16:12 UTC by YuliiRunikov

The end

2021-03-12 16:20 UTC, Denis-CRM requested changes

2021-03-12 16:20 UTC, Denis-CRM commented on www/src/Currency.php
> +
Удали лишнюю строку

2021-03-12 16:20 UTC, Denis-CRM commented on www/src/Currency.php
> +
1

2021-03-12 16:22 UTC, paveldhq requested changes
Добавь инструкцию к использованию

2021-03-12 21:56 UTC, paveldhq commented on README.md
> +./fixer set:rates https://manezh.bitrix.uno/rest 1 l7c37x1gcju8t1cq currency factor
Это `публичный` репозиторий.
НЕЛЬЗЯ комитить пароли и токены

2021-03-12 22:06 UTC, paveldhq requested changes
1. в этом проекте папки `env` и `php-cli` ничего не делают. Удали
2. годного докерфайла нет
3. годного тревис-файла нет
4. все файлы из `www` перенеси на уровень выше

Внимательнее

2021-03-12 22:06 UTC, paveldhq commented on README.md
> +./fixer set:rates https://manezh.bitrix.uno/rest 1 l7c37x1gcju8t1cq EUR 5
код для выполнения в консоли должен быть обрамлен в символы "`", например:

`/fixer set:rates https://manezh.bitrix.uno/rest 1 l7c37x1gcju8t1cq EUR 5`

2021-03-12 22:06 UTC, paveldhq commented on www/src/Currency.php
> +
лишние строки

2021-03-12 22:06 UTC, paveldhq commented on www/src/Currency.php
> +
лишние строки

2021-03-12 22:06 UTC, paveldhq commented on www/src/Currency.php
> +  public function setToken($token) {
поправь форматирование файла
функции не должны начинаться с разным отступом

2021-03-16 09:12 UTC, paveldhq requested changes
Зачем в репозитории бинарник композера?

2021-03-16 09:12 UTC, paveldhq commented on Dockerfile
> +
бред

2021-03-16 14:37 UTC, merged